base_url = "https://timcrain.com"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "base16-tomorrow-night", filename = "syntax-theme-dark.css" },
    { theme = "base16-tomorrow", filename = "syntax-theme-light.css" },
]
extra_syntaxes_and_themes = ["highlight_themes/base16-textmate/Themes"]

[extra]
# Put all your custom variables here
