base_url = "https://timcrain.com"
compile_sass = true
build_search_index = true

[markdown.highlighting]
error_on_missing_language = true
dark_theme = "base16-tomorrow-night"
light_theme = "base16-tomorrow"
extra_themes = [
    "highlight_themes/base16-tomorrow-night.json",
    "highlight_themes/base16-tomorrow.json",
]

[extra]
author = "Timothy Crain"
